version: '3'

services:
  app:
    image: ghcr.io/verifiedjoseph/parrot:1.8.6
    container_name: Parrot
    ports:
      - '8080:8080'
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
