services:
  workspace:
    build:
      context: ./workspace
    tty: true
    volumes:
      - ../:/parrot
      - node_modules:/parrot/node_modules
    working_dir: /parrot

  nginx:
    build:
      context: ./nginx
    ports:
      - 8080:8080
    volumes:
      - ../:/parrot:ro

volumes:
  node_modules:
