name: Code quality

on:
  pull_request:
    paths:
      - "**.js"
      - ".github/workflows/code-quality.yml"
  push:
    branches: main
    paths:
      - "**.js"
      - ".github/workflows/code-quality.yml"

permissions:
  contents: read

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout code
      uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0

    - name: Setup node
      uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4.0.0
      with:
        node-version: 18.18.0
        cache: 'npm'

    - name: Installing dependencies
      run: npm ci

    - name: Run ESLint
      run: npm run lint
