name: Code quality

on:
  pull_request:
    paths:
      - "**.js"
      - ".github/workflows/js-code-quality.yml"
  push:
    branches: main
    paths:
      - "**.js"
      - ".github/workflows/js-code-quality.yml"

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v3.2.0

    - name: Setup node
      uses: actions/setup-node@v3.5.1
      with:
        node-version: 18
        cache: 'npm'

    - name: Installing dependencies
      run: npm ci

    - name: Run ESLint
      run: npm run lint
